config/routes.rb
Rails.application.routes.draw do
  resources :books

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "books#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
    @genres = ["技術書", "小説", "ビジネス書","自己啓発","絵本"];
    require 'net/http'
    require 'json'

    def fetch_posts
      url = URI.parse('https://jsonplaceholder.typicode.com/posts')
      http = Net::HTTP.new(url.host, url.port)
      http.use_ssl = true

      request = Net::HTTP::Get.new(url.request_uri)
      response = http.request(request)

      if response.code == '200'
        posts = JSON.parse(response.body)
        return posts
      else
        return []
      end
    end

    @posts = fetch_posts
    @date = Time.now
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy!

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <p>
    <strong>Title:</strong>
    <%= book.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= book.description %>
  </p>

</div>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
<div class="mx-4">
  <% if book.errors.any? %>
    <div class="text-red-500">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-4">
    <%= form.label :title, class: "block" %>
    <%= form.text_field :title, class: "border rounded-md p-2" %>
  </div>

  <div class="mb-4">
    <%= form.label :description, class: "block" %>
    <%= form.text_area :description, class: "border rounded-md p-2" %>
  </div>

  <div>
    <%= form.submit class: "bg-blue-500 text-white px-4 py-2 rounded-md" %>
  </div>
</div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", @book %> |
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="text-4xl font-bold mb-8">Books</h1>

<div>
  <ul class="flex gap-4 border-b-2">
    <% @genres.each do |genre| %>
      <li class="text-blue-500"><%= genre %></li>
    <% end %>
  </ul>
</div>

<div id="books">
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>ID</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td><%= book.title %></td>
          <td><%= book.description %></td>
          <td><%= book.id %></td>
          <td><%= link_to "Show", book_path(book), class: 'inline-block bg-green-500 text-white px-4 py-2 rounded hover:opacity-80' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<hr />
<%
=begin%>
 <div>
  <% @posts.each do |post| %>
    <div id=<%= post['id'] %>>
      <h2>【ID:<%= post['id'] %>】<%= post['title'] %></h2>
      <p><%= post['body'] %></p>
    </div>
  <% end %>
</div> 
<%
=end%>
<h2><%= @date %></h2>
<h2><%= @date.strftime("%Y年%m月%d日%H時%M分") %></h2>

app/views/books/new.html.erb
<div class="bg-blue-500 p-4 mb-4">
  <h1 class="text-white text-2xl">New book</h1>
</div>

<%= render "form", book: @book %>

<br>

<div class="mx-4">
  <%= link_to ">>Back", books_path %>
</div>

app/views/books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @book %>

<div>
  <%= link_to "Edit this book", edit_book_path(@book) %> |
  <%= link_to "Back to books", books_path %>

  <%= button_to "Destroy this book", @book, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsDokusyu</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://cdn.tailwindcss.com"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <header>
    <nav class="bg-gray-800">
      <div class="container mx-auto flex items-center p-4">
        <a href="/" class="text-white
          text-2xl font-bold mr-8">RailsDokusyu</a>  
        <ul class="flex gap-5">
          <li><a href="/books" class="text-white">書籍一覧</a></li>
          <li><a href="/books/new" class="text-white">追加</a></li>
        </ul>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>